version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: medoed_db
      POSTGRES_USER: medoed_user
      POSTGRES_PASSWORD: medoed
      POSTGRES_MULTIPLE_DATABASES: medoed_db,mlflow_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    restart: always

  medoedai:
    build: .
    container_name: medoedai
    depends_on:
      - redis
    ports:
      - "5050:5050"
    environment:
      - TORCHSERVE_URL=http://serving:8080/predictions/medoedai_model
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./:/app
    working_dir: /app
    command: ["python", "main.py"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  celery-worker:
    build: .
    container_name: celery-worker
    depends_on:
      - medoedai
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./:/app
    working_dir: /app
    command: ["celery", "-A", "tasks.celery_tasks", "worker", "--loglevel=info"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
              
  pytorch-gpu:
    image: pytorch/pytorch:latest
    container_name: pytorch-gpu
    depends_on:
      - celery-worker    
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./workspace:/workspace
      - ./models:/models
    working_dir: /workspace
    command: ["sleep", "infinity"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  pgdata:
