services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: medoed_db
      POSTGRES_USER: medoed_user
      POSTGRES_PASSWORD: medoed
      POSTGRES_MULTIPLE_DATABASES: medoed_db,mlflow_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    restart: always

  medoedai:
    build: .
    container_name: medoedai
    depends_on:
      - serving
      - redis
    ports:
      - "5050:5050"
    environment:
      - TORCHSERVE_URL=http://serving:8080/predictions/medoedai_model
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./:/app
    working_dir: /app
    command: ["python", "main.py"]

  celery-worker:
    build: .
    container_name: celery-worker
    depends_on:
      - medoedai
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./:/app
    working_dir: /app
    command: ["celery", "-A", "tasks.celery_tasks", "worker", "--loglevel=info"]

  serving:
    image: pytorch/torchserve:latest
    container_name: serving
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - MODEL_STORE=/models
      - TS_MODEL_NAME=medoedai_model
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-}
    volumes:
      - ./models:/models
    command: ["torchserve", "--start", "--model-store", "/models", "--models", "medoedai_model.mar"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-0}
              capabilities: [gpu]

  pytorch-gpu:
    image: pytorch/pytorch:latest
    container_name: pytorch-gpu
    depends_on:
      - celery-worker    
    restart: unless-stopped
    ports:
      - "8080:8080"  # если нужно API
      - "8081:8081"  # управление TorchServe
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-}
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./workspace:/workspace
      - ./models:/models
    working_dir: /workspace
    command: ["sleep", "infinity"]  # Работает в фоне, ты заходишь и запускаешь, что хочешь
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-1}
              capabilities: [gpu]     

volumes:
  pgdata:
